version: '3'
services:
  
  httpd:
    container_name: httpd_magento2
    build:
      context: ./httpd
    volumes:
      - ./mage/magento2:/var/www/html
      - ./httpd/init.sh:/etc/init.sh
    ports:
      - "8081:80"
      - "8082:433"

  db:
    container_name: db_magento2
    build:
      context: ./db
    environment: 
      MYSQL_CLIENT: root 
      MYSQL_PASSWORD: magento20001 
      MYSQL_DATABASE: magento20001 
    volumes: 
      - ./db/init.sh:/etc/init.sh
#     - ./db/data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    container_name: redis_magento2
    build:
      context: ./redis
    
